server:
  port: 8000

eureka:
  client:
    fetch-registry: true # ??? ????? ???
    register-with-eureka: true # ??? ????? ???
    service-url:
      defaultZone: http://localhost:8761/eureka # ??? ?????? ??

spring:
  application:
    name: gateway-service

#  cloud:
#    gateway:
#      routes:
#        - id: user-service
#          uri: http://localhost:64412 # ???? ??, http://localhost:8000/user ? ???? http://localhost:64412 ? ???
#          predicates:
#            - Path=/user/** # ?? gateway ??? /user/**? ???? ?? user-service? ?????? ??
#
#        - id: order-service
#          uri: http://localhost:54412 # ??? ? ??, http://localhost:8000/order ? ???? http://localhost:54412 ? ???
#          predicates:
#            - Path=/order/** # ?? gateway ??? /order/**? ???? ?? order-service? ?????? ??

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**